
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.lang.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * main.java
 *
 * Created on 14 Jan, 2010, 10:39:55 AM
 */

/**
 *
 * @author Puneet
 */
public class main extends javax.swing.JFrame {
    private Connection con;
    private PreparedStatement ps;
    private Statement st;
    private ResultSet rs;
    private String[] s = null;
    private String[] s1=null;
    

    /** Creates new form main */
    public main() throws Exception {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        SAVE = new javax.swing.JButton();
        CANCEL = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton7 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ADDITEM = new javax.swing.JButton();
        ADDRECORD = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setTitle("ADD ITEM");
        jDialog1.setMinimumSize(new java.awt.Dimension(500, 300));
        jDialog1.setModal(true);

        jLabel3.setText("*IMI NO. :-");

        jTextField1.setColumns(5);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jLabel4.setText("*ITEM NAME:-");

        jTextArea1.setColumns(30);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(4);
        jScrollPane1.setViewportView(jTextArea1);

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        CANCEL.setText("CANCEL");
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(SAVE)
                        .addGap(51, 51, 51)
                        .addComponent(CANCEL))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAVE)
                    .addComponent(CANCEL))
                .addGap(25, 25, 25))
        );

        jDialog2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog2.setTitle("ADD RECORD");
        jDialog2.setMinimumSize(new java.awt.Dimension(650, 400));
        jDialog2.setModal(true);

        jLabel5.setText("*IMI NO. :-");

        jLabel6.setText("*ITEM NAME :-");

        jLabel7.setText("*PARTY :-");

        jLabel8.setText("*ORDER NO. :-");

        jLabel9.setText("*ORDER DATE (eg. 26-01-2010) :-");

        jLabel10.setText("*QUANTITY :-");

        jLabel11.setText("DATE :-");

        jTextField2.setColumns(3);
        jTextField2.setText("0");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });

        jTextField3.setColumns(5);

        jTextField7.setColumns(6);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });

        jTextArea2.setColumns(30);
        jTextArea2.setEditable(false);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(3);
        jScrollPane2.setViewportView(jTextArea2);

        jTextField6.setColumns(8);
        jTextField6.setText(new SimpleDateFormat("dd-MM-yyyy").format(new Date()));

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea3.setColumns(30);
        jTextArea3.setRows(4);
        jScrollPane3.setViewportView(jTextArea3);

        jFormattedTextField1.setColumns(8);
        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jLabel15.setText(" ");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialog2Layout.createSequentialGroup()
                                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialog2Layout.createSequentialGroup()
                                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(jDialog2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(34, 34, 34)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(100, Short.MAX_VALUE))))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15))
        );

        jTextField2.selectAll();

        jDialog2.setModal(true);

        jDialog3.setMinimumSize(new java.awt.Dimension(1000, 650));
        jDialog3.setModal(true);

        jLabel13.setText("ENTER IMI NO. :-");

        jTextField4.setColumns(8);
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jButton3.setText("REMOVE SELECTED ENTRY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel14.setText("TOTAL QUANTITY REQUIRED:-");

        jTextField5.setColumns(6);
        jTextField5.setEditable(false);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {""};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        jButton4.setText("GENERATE PRINTABLE FILE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("REMOVE ALL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel16.setText("(ORDER NO.)             (IMI no.)(ITEM NAME)            (QUANTITY)                (PARTY NAME)");

        jLabel23.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(408, 408, 408))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(122, 122, 122))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(624, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(541, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel16)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("IMI NO.", jPanel2);

        jLabel17.setText("STARTING DATE :-");

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel18.setText("ENDING DATE :-");

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel19.setText("(eg. 26-01-2010)");

        jButton6.setText("FIND");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {""};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList2);

        jButton7.setText("GENERATE PRINTABLE VERSION");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel20.setText("TOTAL QUANTITY REQUIRED :-");

        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setColumns(6);
        jTextField8.setEditable(false);

        jButton9.setText("REMOVE SELECTED");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel21.setText(" ");

        jLabel22.setText("(ORDER NO.)      (ENTERY DATE:yyyy-mm-dd 00:00:00)      (IMI no)(ITEM NAME)             (QUANTITY)              (PARTY NAME)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(jButton9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel19)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jLabel19))
                .addGap(15, 15, 15)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jLabel20)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DATE", jPanel3);

        jDialog3.getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SCEARCH BY :-");
        jDialog3.getContentPane().add(jLabel12, java.awt.BorderLayout.PAGE_START);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INDIA MEDICO INSTRUMENTS");
        setBounds(new java.awt.Rectangle(2, 2, 700, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Comic Sans MS", 0, 10));
        setMinimumSize(new java.awt.Dimension(700, 600));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 30));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INDIA MEDICO INSTRUMENTS");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        ADDITEM.setText("ADD/EDIT ITEM");
        ADDITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDITEMActionPerformed(evt);
            }
        });

        ADDRECORD.setText("ADD RECORD");
        ADDRECORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDRECORDActionPerformed(evt);
            }
        });

        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADDRECORD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(SEARCH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(ADDITEM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ADDITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ADDRECORD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_END);
        CurrentDate cd=new CurrentDate();
        cd.setDaemon(true);
        cd.start();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADDITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDITEMActionPerformed
        jTextField1.setText("");
        jTextArea1.setText("");
        jDialog1.setVisible(true);
    }//GEN-LAST:event_ADDITEMActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        
        jTextField4.setText("");
       jTextField8.setText("");
       jList1.setModel(new javax.swing.AbstractListModel() {
    String[] strings = {""};
    public int getSize() { return strings.length; }
    public Object getElementAt(int i) { return strings[i]; }
});
    jList2.setModel(new javax.swing.AbstractListModel() {
    String[] strings = {""};
    public int getSize() { return strings.length; }
    public Object getElementAt(int i) { return strings[i]; }
});
        jTextField5.setText("");
        jFormattedTextField2.setText("");
        jFormattedTextField3.setText("");
        jDialog3.setVisible(true);
        jLabel21.setText(" ");
        jLabel23.setText(" ");
    }//GEN-LAST:event_SEARCHActionPerformed

    private void ADDRECORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDRECORDActionPerformed
        jTextField3.setText("");
        jTextField2.setText("0");
        jTextField7.setText("");
        jTextArea2.setText("");
        jTextArea3.setText("");
        jFormattedTextField1.setText("");
        jLabel15.setText(" ");
        jDialog2.setVisible(true);
    }//GEN-LAST:event_ADDRECORDActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        try {
            con = DriverManager.getConnection("jdbc:odbc:Clinic;UID=system;PWD=puneet");
            ps=con.prepareStatement("delete from item where imino='"+jTextField1.getText()+"'");
            ps.executeUpdate();
            ps.close();
            ps = con.prepareStatement("insert into item values('"+jTextField1.getText()+"','"+jTextArea1.getText()+"')");
            ps.executeUpdate();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println("hi u r mad");
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialog1.dispose();
    }//GEN-LAST:event_SAVEActionPerformed

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed
        jDialog1.dispose();
    }//GEN-LAST:event_CANCELActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
      try {
            con = DriverManager.getConnection("jdbc:odbc:Clinic;UID=system;PWD=puneet");
            st=con.createStatement();
		rs=st.executeQuery("select * from item where imino='"+jTextField1.getText()+"'");
                jTextArea1.setText("");
		while(rs.next())
		{
                        jTextArea1.setText(rs.getString("item_name"));
		}
            rs.close();
            st.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println("INVALID IMINO");
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
         try {
            con = DriverManager.getConnection("jdbc:odbc:Clinic;UID=system;PWD=puneet");
            st=con.createStatement();
		rs=st.executeQuery("select * from item where imino='"+jTextField7.getText()+"'");
                jTextArea2.setText("");
		while(rs.next())
		{
                        jTextArea2.setText(rs.getString("item_name"));
		}
            rs.close();
            st.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println("INVALID IMINO");
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField7FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try {
           // String s=getDate(jFormattedTextField1.getText());
            con = DriverManager.getConnection("jdbc:odbc:Clinic;UID=system;PWD=puneet");
            ps = con.prepareStatement("insert into manufacture values('"+jTextField7.getText()+"','"+jTextArea2.getText()+"','"+jTextArea3.getText()+"','"+getDate(jTextField6.getText())+"','"+getDate(jFormattedTextField1.getText())+"','"+jTextField3.getText()+"',"+jTextField2.getText()+")");
     //       System.out.println("insert into manufacture values('"+jTextField7.getText()+"','"+jTextArea2.getText()+"','"+jTextArea3.getText()+"','"+getDate(jTextField6.getText())+"','"+getDate(jFormattedTextField1.getText())+"','"+jTextField3.getText()+"',"+jTextField2.getText()+")");
            ps.executeUpdate();
            ps.close();
            con.close();
             jTextField3.setText("");
             jTextField2.setText("0");
             jTextField7.setText("");
             jTextArea2.setText("");
             jTextArea3.setText("");
             jFormattedTextField1.setText("");
             jLabel15.setText(" ");
        //    jDialog2.dispose();
        } catch (SQLException ex) {
            System.out.println("wrong entry");
            jLabel15.setText("SOORY :- YOU GAVE A WRONG ENTRY..CHECK IMI NO. AND DATE FORMAT");
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
private String getDate(String s)
{
    String f = null;
    try {
        int i = Integer.parseInt(s.substring(3, 5));
        String m = "__";
        // System.out.println(i);
        switch (i) {
            case 1:
                m = "Jan";
                break;
            case 2:
                m = "Feb";
                break;
            case 3:
                m = "Mar";
                break;
            case 4:
                m = "Apr";
                break;
            case 5:
                m = "May";
                break;
            case 6:
                m = "Jun";
                break;
            case 7:
                m = "Jul";
                break;
            case 8:
                m = "Aug";
                break;
            case 9:
                m = "Sep";
                break;
            case 10:
                m = "Oct";
                break;
            case 11:
                m = "Nov";
                break;
            case 12:
                m = "Dec";
                break;
        }
        f = "" + s.substring(0, 3) + m + s.substring(5);
        System.out.println(f);
    } catch (Exception e) {
        jLabel15.setText("SOORY :- CHECK DATE FORMAT");
    }
    return f;

}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialog2.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
jTextField2.selectAll();
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        try {
            jLabel23.setText(" ");
            con = DriverManager.getConnection("jdbc:odbc:Clinic;UID=system;PWD=puneet");
            st=con.createStatement();

		rs=st.executeQuery("select count(*),sum(quantity) from manufacture where imino='"+jTextField4.getText()+"'");
                while(rs.next())
                {
                    s=new String[Integer.parseInt(rs.getString("count(*)"))];
                    jTextField5.setText(rs.getString("sum(quantity)"));
                }
                rs.close();
                jList1.removeAll();
                rs=st.executeQuery("select * from manufacture where imino='"+jTextField4.getText()+"'");
                int i=0;
		while(rs.next())
		{
                        s[i]="("+rs.getString("order_no")+")     (IMI no.="+rs.getString("imino")+")("+rs.getString("item_name")+")        ("+rs.getString("quantity")+")     "+rs.getString("party_name");
                        i++;
		}
                jList1.setModel(new javax.swing.AbstractListModel() {
      //           String[] strings =s;
                     public int getSize() { return s.length; }
                    public Object getElementAt(int i) { return s[i]; }
});
            rs.close();
            st.close();
            con.close();

        } catch (SQLException ex) {
            System.out.println("INVALID IMINO");
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String slist=(String)jList1.getSelectedValue();
       // System.out.println(s1);
      
        try {
            con = DriverManager.getConnection("jdbc:odbc:Clinic;UID=system;PWD=puneet");
            ps=con.prepareStatement("delete from manufacture where imino='"+jTextField4.getText()+"' AND order_no='"+slist.substring(slist.indexOf("(")+1, slist.indexOf(")"))+"'");
            ps.executeUpdate();
           ps.close();
            st=con.createStatement();
		rs=st.executeQuery("select count(*),sum(quantity) from manufacture where imino='"+jTextField4.getText()+"'");
                while(rs.next())
                {
                    s=new String[Integer.parseInt(rs.getString("count(*)"))];
                    jTextField5.setText(rs.getString("sum(quantity)"));
                }
                rs.close();

                rs=st.executeQuery("select * from manufacture where imino='"+jTextField4.getText()+"'");
                int i=0;
		while(rs.next())
		{
                        s[i]="("+rs.getString("order_no")+")     (IMI no.="+rs.getString("imino")+")("+rs.getString("item_name")+")        ("+rs.getString("quantity")+")     "+rs.getString("party_name");
                        i++;
		}
                jList1.setModel(new javax.swing.AbstractListModel() {
      //           String[] strings =s;
                     public int getSize() { return s.length; }
                    public Object getElementAt(int i) { return s[i]; }
});
            rs.close();
            st.close();
            con.close();

        } catch (Exception ex) {
            System.out.println("some thing wrong with REMOVE SELECTED ITEM BUTTON");
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

       try {
            con = DriverManager.getConnection("jdbc:odbc:Clinic;UID=system;PWD=puneet");
            ps=con.prepareStatement("delete from manufacture where imino='"+jTextField4.getText()+"'");
            ps.executeUpdate();
           ps.close();
           /*s=new String[1];
           rs=st.executeQuery("select * from manufacture where imino='"+jTextField4.getText()+"'");
           int i=0;
           while(rs.next())
           {

           s[i]="("+rs.getString("order_no")+")     (IMI no.="+rs.getString("imino")+")("+rs.getString("item_name")+")        ("+rs.getString("quantity")+")     "+rs.getString("party_name");
           i++;
           }
           jList1.setModel(new javax.swing.AbstractListModel() {
           //           String[] strings =s;
           public int getSize() { return s.length; }
           public Object getElementAt(int i) { return s[i]; }
           });
           rs.close();
           st.close();*/
           con.close();
           jList1.setModel(new javax.swing.AbstractListModel() {
                      String[] strings ={""};
           public int getSize() { return strings.length; }
           public Object getElementAt(int i) { return strings[i]; }
           });


        } catch (Exception ex) {
            System.out.println("some thing wrong with REMOVE ALL BUTTON");
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            jLabel21.setText(" ");
            con = DriverManager.getConnection("jdbc:odbc:Clinic;UID=system;PWD=puneet");
            st=con.createStatement();

		rs=st.executeQuery("select count(*),sum(quantity) from manufacture where Entry_date BETWEEN '"+getDate(jFormattedTextField2.getText())+"' AND '"+getDate(jFormattedTextField3.getText())+"'");
                while(rs.next())
                {
                    s1=new String[Integer.parseInt(rs.getString("count(*)"))];
                    jTextField8.setText(rs.getString("sum(quantity)"));
                }
                rs.close();
           
                rs=st.executeQuery("select * from manufacture where Entry_date BETWEEN '"+getDate(jFormattedTextField2.getText())+"' AND '"+getDate(jFormattedTextField3.getText())+"'");
                int i=0;
		while(rs.next())
		{
                        s1[i]="("+rs.getString("order_no")+")     (Entry Date:"+rs.getString("entry_date")+")     (IMI no.="+rs.getString("imino")+")("+rs.getString("item_name")+")        ("+rs.getString("quantity")+")     "+rs.getString("party_name");
                        i++;
		}
                jList2.setModel(new javax.swing.AbstractListModel() {
      //           String[] strings =s;
                     public int getSize() { return s1.length; }
                    public Object getElementAt(int i) { return s1[i]; }
});
            rs.close();
            st.close();
            con.close();
            
        } catch (Exception ex) {
            jLabel21.setText("SORRY : INVALID DATE");
            System.out.println("something wrong with find button");
           
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         String slist=(String)jList2.getSelectedValue();
        try {
            con = DriverManager.getConnection("jdbc:odbc:Clinic;UID=system;PWD=puneet");

            System.out.println("delete from manufacture where imino='"+slist.substring(slist.indexOf("=")+1, slist.indexOf(")", slist.indexOf("=")))+"' AND order_no='"+slist.substring(slist.indexOf("(")+1, slist.indexOf(")"))+"'");
              ps=con.prepareStatement("delete from manufacture where imino='"+slist.substring(slist.indexOf("=")+1, slist.indexOf(")", slist.indexOf("=")))+"' AND order_no='"+slist.substring(slist.indexOf("(")+1, slist.indexOf(")"))+"'");
              
            ps.executeUpdate();
           ps.close();
            st=con.createStatement();

		rs=st.executeQuery("select count(*),sum(quantity) from manufacture where Entry_date BETWEEN '"+getDate(jFormattedTextField2.getText())+"' AND '"+getDate(jFormattedTextField3.getText())+"'");
                while(rs.next())
                {
                    s1=new String[Integer.parseInt(rs.getString("count(*)"))];
                    jTextField8.setText(rs.getString("sum(quantity)"));
                }
                rs.close();

                rs=st.executeQuery("select * from manufacture where Entry_date BETWEEN '"+getDate(jFormattedTextField2.getText())+"' AND '"+getDate(jFormattedTextField3.getText())+"'");
                int i=0;
		while(rs.next())
		{
                        s1[i]="("+rs.getString("order_no")+")     (Entry Date:"+rs.getString("entry_date")+")     (IMI no.="+rs.getString("imino")+")("+rs.getString("item_name")+")        ("+rs.getString("quantity")+")     "+rs.getString("party_name");
                        i++;
		}
                jList2.setModel(new javax.swing.AbstractListModel() {
      //           String[] strings =s;
                     public int getSize() { return s1.length; }
                    public Object getElementAt(int i) { return s1[i]; }
});
            rs.close();
            st.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println("something wrong with find button");
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            String sv=new String();
            File f=new File("C:/IMI");
            boolean b1=f.mkdirs();
            String str="C:/IMI/IMI-" + jTextField4.getText() + ".txt";
            File fi = new File(str);
         
            boolean b=fi.createNewFile();
         
            FileWriter fw = new FileWriter(fi);
         
            BufferedWriter bw = new BufferedWriter(fw, 3000);
        
            for(int k=0;k<s.length;k++)
            {
                sv=sv+"#"+k+"#  "+s[k]+"                  ";
            }
        
            bw.write(sv);
        
            bw.close();
            fw.close();
            jLabel23.setText("FILE GENERATED AT:- "+str);

        } catch (IOException iO) {
            System.out.println("CANNOT WRITE FILE"+iO.getMessage());
            jLabel23.setText("SORRY : CANNOT BE CREATEED FILE");

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    try {
            String sv=new String();
            File f=new File("C:/IMI");
            boolean b1=f.mkdirs();
            String str="C:/IMI/IMI-" +jFormattedTextField2.getText()+" to "+jFormattedTextField3.getText()+".txt";
            File fi = new File(str);

            boolean b=fi.createNewFile();

            FileWriter fw = new FileWriter(fi);

            BufferedWriter bw = new BufferedWriter(fw, 3000);

            for(int k=0;k<s1.length;k++)
            {
                sv=sv+"#"+k+"#  "+s1[k]+"                  ";
            }

            bw.write(sv);

            bw.close();
            fw.close();
            jLabel21.setText("FILE GENERATED AT:- "+str);

        } catch (IOException iO) {
            System.out.println("CANNOT WRITE FILE"+iO.getMessage());
            jLabel21.setText("SORRY : CANNOT BE CREATEED FILE");

        }
    }//GEN-LAST:event_jButton7ActionPerformed
class CurrentDate extends Thread
	{
		public void run()
		{
			Date d;
			SimpleDateFormat simpDate=new SimpleDateFormat("EEEE    dd-MMM-yy    hh:mm:ss a");
			for(int i=1;i>0;i++)
			{
				d=new Date();
				jLabel2.setText(simpDate.format(d));
			}
		}
	}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new main().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDITEM;
    private javax.swing.JButton ADDRECORD;
    private javax.swing.JButton CANCEL;
    private javax.swing.JButton SAVE;
    private javax.swing.JButton SEARCH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

}
